project:
  name: quickstart-jfrog-container-registry
  owner: quickstart-eng@amazon.com
  s3_object_acl: public-read
  s3_bucket: ''
  s3_regional_buckets: True
  lambda_source_path: submodules/quickstart-jfrog-artifactory/submodules/quickstart-amazon-eks/functions/source
  lambda_zip_path: submodules/quickstart-jfrog-artifactory/submodules/quickstart-amazon-eks/functions/packages
  regions:
    - us-west-2


tests:
#  jfrog-container-registry-ec2-postgres:
#    parameters:
#      KeyPairName: "$[taskcat_getkeypair]"
#      JcrVersion: 7.2.1
#      RemoteAccessCidr: "10.0.0.0/16"
#      AccessCidr: "10.0.0.0/16"
#      AvailabilityZones: "$[taskcat_genaz_2]"
#      DatabasePassword: "$[taskcat_genpass_8A]"
#      QsS3BucketName: "$[taskcat_autobucket]"
#      QsS3KeyPrefix: "quickstart-jfrog-container-registry/"
#      QsS3BucketRegion: "$[taskcat_current_region]"
#      KeystorePassword: "$[taskcat_genpass_8A]"
#      AnsibleVaultPass: "$[taskcat_genpass_8A]"
#      JcrServerName: "artifactory"
#      SmCertName: "override"
#      MasterKey: "override"
#      MultiAzDatabase: "false"
#    template: templates/jfrog-container-registry-ec2-master.template.yaml
#    regions:
#      - us-east-1
#  jfrog-container-registry-ecs-mysql:
#    parameters:
#      KeyPairName: "$[taskcat_getkeypair]"
#      RemoteAccessCidr: "10.0.0.0/16"
#      AccessCidr: "10.0.0.0/16"
#      AvailabilityZones: "$[taskcat_genaz_2]"
#      DatabasePassword: "$[taskcat_genpass_8A]"
#      QsS3BucketName: "$[taskcat_autobucket]"
#      QsS3KeyPrefix: "quickstart-jfrog-container-registry/"
#      QsS3BucketRegion: "$[taskcat_current_region]"
#      DatabaseInstance: "db.m4.large"
#      # DatabaseEngine: MySQL
#      JcrVersion: "7.2.1"
#      NumberOfSecondary: "2"
#      AnsibleVaultPass: "$[taskcat_genpass_8A]"
#      JcrServerName: "artifactory"
#      MasterKey: "override"
#      SmCertName: "override"
#      MultiAzDatabase: "false"
#    template: templates/jfrog-container-registry-ecs-master.template.yaml
#    regions:
#      - us-east-1
#  jfrog-container-registry-eks-east-mysql:
#    parameters:
#      KeyPairName: "$[taskcat_getkeypair]"
#      RemoteAccessCidr: "10.0.0.0/16"
#      AccessCidr: "10.0.0.0/16"
#      AvailabilityZones: "$[taskcat_genaz_3]"
#      # DatabaseEngine: MySQL
#      DatabasePassword: "$[taskcat_genpass_8A]"
#      QsS3BucketName: "$[taskcat_autobucket]"
#      QsS3KeyPrefix: "quickstart-jfrog-container-registry/"
#      QsS3BucketRegion: "$[taskcat_current_region]"
#      DatabaseInstance: "db.m5.large"
#      JcrVersion: "7.2.1"
#      JcrServerName: "artifactory"
#      MasterKey: "override"
#      SmCertName: "override"
#      MultiAzDatabase: "false"
#    template: templates/jfrog-container-registry-eks-master.template.yaml
#    regions:
#      - us-east-2
