project:
  name: quickstart-jfrog-container-registry
  owner: quickstart-eng@amazon.com
  s3_object_acl: public-read
  # lambda_source_path: submodules/quickstart-jfrog-artifactory/submodules/quickstart-amazon-eks/functions/source
  # lambda_zip_path: submodules/quickstart-jfrog-artifactory/submodules/quickstart-amazon-eks/functions/packages
  s3_object_acl: public-read
  s3_regional_buckets: True
  s3_bucket: tcat-422383ecc658557f9a377abae675aac0  # commercial accounts
  regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - eu-north-1
    - eu-south-1 # No EKS
    - ap-southeast-2
    - ca-central-1 # No EKS
    - sa-east-1
    - af-south-1

tests:
  # jfrog-jcr-7102:
  #   auth:
  #     default: default
  #     us-gov-west-1: gov
  #     us-gov-east-1: gov
  #   parameters:
  #     AvailabilityZone: "$[taskcat_genaz_1]"
  #     KeyPairName: "ArtCldFrm1"
  #     # ArtifactVersion: 7.10.2
  #     RemoteAccessCidr: "0.0.0.0/0"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #   template: templates/jfrog-ami-master.template.yaml
  #   regions:
  #     - us-east-1

  jfrog-container-registry-ec2:
    parameters:
      KeyPairName: "ArtCldFrm1"
      AvailabilityZones: "$[taskcat_genaz_2]"
      AccessCidr: "0.0.0.0/0"
      RemoteAccessCidr: "0.0.0.0/0"
      JcrVersion: 7.10.2
      JcrServerName: "artifactory"
      SmLicenseCertName: "jfrog-artifactory"
      MasterKey: "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
      KeystorePassword: "$[taskcat_genpass_8A]"
      AnsibleVaultPass: "$[taskcat_genpass_8A]"
      MultiAzDatabase: "false"
      DatabasePassword: "$[taskcat_genpass_8A]"
      DatabaseInstance: "db.m5.large"
      DatabasePassword: "$[taskcat_genpass_8A]"
      QsS3BucketName: "$[taskcat_autobucket]"
      QsS3KeyPrefix: "quickstart-jfrog-container-registry/"
      QsS3BucketRegion: "$[taskcat_current_region]"
    template: templates/jfrog-container-registry-ec2-master.template.yaml
    regions:
      - us-east-1

  jfrog-container-registry-ecs:
    parameters:
      KeyPairName: "ArtCldFrm1"
      RemoteAccessCidr: "0.0.0.0/0"
      AccessCidr: "0.0.0.0/0"
      AvailabilityZones: "$[taskcat_genaz_2]"
      DatabasePassword: "$[taskcat_genpass_8A]"
      DatabaseInstance: "db.m5.large"
      #DatabaseEngine: MySQL
      JcrVersion: "7.10.2"
      NumberOfSecondary: "2"
      AnsibleVaultPass: "$[taskcat_genpass_8A]"
      JcrServerName: "artifactory"
      MasterKey: "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
      SmLicenseCertName: "jfrog-artifactory"
      MultiAzDatabase: "false"
      QsS3BucketName: "$[taskcat_autobucket]"
      QsS3KeyPrefix: "quickstart-jfrog-container-registry/"
      QsS3BucketRegion: "$[taskcat_current_region]"
    template: templates/jfrog-container-registry-ecs-master.template.yaml
    regions:
       - us-east-1
       - us-west-2
  #       - us-east-2
  #       # - us-west-1
  #       - eu-central-1
  #       - eu-west-1
  #       - eu-west-2
  #       # - eu-west-3
  #       # - ap-southeast-2
  #       # - eu-north-1
  #       # - ca-central-1
  #       # - sa-east-1
  #       # - eu-south-1
  #       # - af-south-1
  # jfrog-container-registry-eks:
  #   parameters:
  #     KeyPairName: "$[taskcat_getkeypair]"
  #     RemoteAccessCidr: "10.0.0.0/16"
  #     AccessCidr: "10.0.0.0/16"
  #     AvailabilityZones: "$[taskcat_genaz_3]"
  #     DatabasePassword: "$[taskcat_genpass_8A]"
  #     DatabaseInstance: "db.m5.large"
  #   #  JcrVersion: "7.2.1"
  #     JcrServerName: "artifactory"
  #     MasterKey: "override"
  #     SmLicenseCertName: "override"
  #     MultiAzDatabase: "false"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-container-registry/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #   template: templates/jfrog-container-registry-eks-master.template.yaml
  #   regions:
  #     # - us-east-1
  #     - us-west-2
  #     - us-east-2
  #     - eu-west-1
  #     - eu-west-2
  #     # - eu-west-3
  #     - eu-central-1
